### PR TITLE
Adding a few more predefined queries into the constants

### PR DESCRIPTION
**Pull request by heslegrave**
Hi @niklascp, I needed an integration to ConnectedCars.io for Home-Assistant, since i use "MinVolkswagen".
I was so lucky to see that you have already made this fine PyPi, so I just based my integration on that.
It seems you may be using HA yourself, so I was looking to see if you had made an integration yourself. I did not find it so I made one myself.

Review on my integration PR indicates that the queries should reside in the 3.party lib, so I am asking if you would accept this PR and create a new PyPi?

The HA PR is here: https://github.com/home-assistant/core/pull/37997

### CODE REVIEW

**Comment by esbenr** [comment]
Hi @heslegrave and @niklascp.

I have also been working on an connectedcars.io integration for Home Assistant. Also using @niklascp's library.
Maybe we should join forces to maintain and develop this?
As far as I can see, this needs to be reviewed and merged in order to get the Home Assistant component released.

@niklascp could you please approve this PR or maybe bump @heslegrave and I to write access, so we can help maintaining this?

Kind regards,
Esben

**Comment by heslegrave** [comment]
Hi @esbenr and @niklascp,

I am okay with joining forces on this. Not really because I have a lot of time for it, I just made th HA integration because I wanted it and was delighted to see @niklascp had made this so I did not need to. I am running the version of connected cars I have made as a custom integration in HA for now, and was hoping that @niklascp would reply on this PR after a summer vacation or something - it does not seem so though.

We could fork it or just make our own to get it flowing.

Br Jais

**Comment by niklascp** [comment]
Hi both, Sorry for not responding to this PR sooner. Have you ended up with a fork, or?

I am very interested to get your enhancement into this repo :)

**Comment by niklascp** [comment]
@heslegrave did you make an custom HA-component? Otherwise, you were absolutely right, the main purpose of this package was to provide a ConnectedCars integration for HA - this is how far I got:
https://gist.github.com/niklascp/6d42fd16d44c172c37489f6f589b09c0

**Comment by heslegrave** [comment]
@niklascp Yes, I did and I am using it myself but sadly the PRs was never completed because I needed to move the queries into your component according to review:
https://github.com/home-assistant/core/pull/37997

also I have made documentation:
https://github.com/home-assistant/home-assistant.io/pull/14053
and branding:
https://github.com/home-assistant/brands/pull/1751

but it all went stale. So I actually ended up starting to create another ConnectedCars PyPi but it had a bug and since I have not had the time to look into it.

So if you also have a version on the way of your own I would like to ask how done it is ? What kind of work is missing currently?

**Comment by esbenr** [comment]
Hi. 
Due to personal reasons, I have been a bit out of the picture lately. But if I can be of any help, I would like to volunteer.
I'm an experienced engineer (not python, though, but many other languages).
It appears as if we've all created three different custom integrations, based on @niklascp's library.
Putting our efforts together would make good sense or distribute the responsibility could also be an option.

Thus I have had a different approach than you. I have created one giant sensor (to rule them all) with all data as attributes.
The reason for this was the design of the API and to reduce the amount of calls to the connectedcars.io API.
My plan was to map the attributes out in template sensors in HA. Anyway. I'm totally on board with your course @niklascp, I think that approach is more HA-ish.

Maybe we should move the custom control into a repo instead of Gist, in order to work more structured on it?

**Pull request merged**
